In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df= pd.read_csv('placement.csv')

In [46]:
df.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [47]:
df= df.iloc[:,1:]

In [45]:
df

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

[100 rows x 0 columns]

In [36]:
plt.scatter(df["cgpa"], df["iq"], c= df["placement"])

KeyError: 'cgpa'

In [ ]:
x= df.iloc[:,0:2]
y = df.iloc[:,-1]

In [37]:
x_train, x_test, y_train, y_test =train_test_split(x,y, test_size = 0.1)

In [38]:
x_test

    cgpa     iq
6    5.7  143.0
69   8.5  120.0
45   6.0   66.0
15   5.1  176.0
54   6.4  141.0
32   7.0  139.0
12   5.4  139.0
42   7.6   89.0
82   6.5   37.0
1    5.9  106.0